import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";
import { ReactNode, Suspense } from "react";
import { auth } from "@/auth";
import { AuthProvider } from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
const sessionKey = new Date().valueOf();
  return (
    // <SessionProvider>
    <AuthProvider session={session} sessionKey={sessionKey}>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <Suspense fallback={null}>
          {children}
          </Suspense>
          <Toaster richColors={true}/>
        </body>
      </html>
    </AuthProvider> 
    // {/* </SessionProvider> */}
  );
}
