import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "sonner";
import { ReactNode, Suspense } from "react";
import { SessionDataProvider } from '@/components/wrapper/SessionDataWrapper'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<SessionDataProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <Suspense fallback={null}>
          {children}
          </Suspense>
          <Toaster richColors={true}/>
        </body>
      </html>
      </SessionDataProvider>
  );
}
